export const graduationCourses = [
  // 🔬 Science
  { label: "B.Sc (Physics)", value: "bsc_physics" },
  { label: "B.Sc (Chemistry)", value: "bsc_chemistry" },
  { label: "B.Sc (Mathematics)", value: "bsc_mathematics" },
  { label: "B.Sc (Botany)", value: "bsc_botany" },
  { label: "B.Sc (Zoology)", value: "bsc_zoology" },
  { label: "B.Sc (Biotechnology)", value: "bsc_biotech" },
  { label: "B.Sc (Microbiology)", value: "bsc_microbiology" },
  { label: "B.Sc (Environmental Science)", value: "bsc_env_sci" },
  { label: "B.Sc (Computer Science)", value: "bsc_cs" },
  { label: "B.Sc (Statistics)", value: "bsc_statistics" },
  { label: "B.Tech (Computer Science)", value: "btech_cs" },
  { label: "B.Tech (Mechanical)", value: "btech_me" },
  { label: "B.Tech (Civil)", value: "btech_civil" },
  { label: "B.Tech (Electrical)", value: "btech_ee" },
  { label: "B.Tech (Electronics & Comm)", value: "btech_ec" },
  { label: "BCA (Computer Applications)", value: "bca" },
  { label: "B.Pharma (Pharmacy)", value: "bpharma" },
  { label: "B.Sc (Nursing)", value: "bsc_nursing" },

  // 💼 Commerce
  { label: "B.Com (General)", value: "bcom_general" },
  { label: "B.Com (Honours)", value: "bcom_hons" },
  { label: "B.Com (Accounting & Finance)", value: "bcom_af" },
  { label: "B.Com (Taxation)", value: "bcom_taxation" },
  { label: "B.Com (Banking & Insurance)", value: "bcom_bi" },
  { label: "BBA (Bachelor of Business Administration)", value: "bba" },
  { label: "BMS (Bachelor of Management Studies)", value: "bms" },
  { label: "BAF (Accounting & Finance)", value: "baf" },

  // 🎨 Arts / Humanities
  { label: "B.A. (English)", value: "ba_english" },
  { label: "B.A. (Hindi)", value: "ba_hindi" },
  { label: "B.A. (History)", value: "ba_history" },
  { label: "B.A. (Geography)", value: "ba_geography" },
  { label: "B.A. (Political Science)", value: "ba_political" },
  { label: "B.A. (Sociology)", value: "ba_sociology" },
  { label: "B.A. (Psychology)", value: "ba_psychology" },
  { label: "B.A. (Economics)", value: "ba_economics" },
  { label: "B.A. (Philosophy)", value: "ba_philosophy" },
  { label: "B.A. (Public Administration)", value: "ba_public_admin" },
  { label: "B.A. (Education)", value: "ba_education" },
  { label: "BJMC (Journalism & Mass Comm)", value: "bjmc" },
  { label: "BSW (Social Work)", value: "bsw" },
  { label: "BFA (Fine Arts)", value: "bfa" },

  // 🏫 Education & Others
  { label: "B.Ed (Education)", value: "bed" },
  { label: "B.El.Ed (Elementary Education)", value: "beled" },
  { label: "B.Li.Sc (Library Science)", value: "blisc" },
  { label: "B.Design (Interior/Fashion/Product)", value: "bdes" },
  { label: "B.Arch (Architecture)", value: "barch" },
  { label: "BHM (Hotel Management)", value: "bhm" },
  { label: "BPT (Physiotherapy)", value: "bpt" },
  { label: "LL.B (Law)", value: "llb" },
];
