import Layout from "@/components/Layout";
import React from "react";
import { useEffect } from "react";

function TermsCondition() {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <Layout>
      <div className="mt-14 bg-gray-100">
        {/* Header Section */}
        <div className="container mx-auto px-4 py-12 text-center">
          <h2 className="text-3xl md:text-4xl font-semibold text-gray-900">
            TERMS & CONDITIONS
          </h2>
        </div>

        {/* Terms Content */}
        <div className="container mx-auto px-4 pb-12">
          <div className="bg-white shadow-md rounded-lg p-6 md:p-10 text-gray-700 text-justify space-y-6">

            <p className="text-base md:text-lg leading-relaxed">
              This document is an electronic record in terms of the Information Technology Act, 2000, and rules thereunder as applicable, and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>

            <p className="text-base md:text-lg leading-relaxed">
              This document is published in accordance with Rule 3 (1) of the Information Technology (Intermediaries Guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of the domain name <a href="https://homentor.in" className="text-blue-700 underline">https://homentor.in</a> (Website), including the related mobile site (hereinafter referred to as ‘Platform’). The Platform is owned by HOMENTOR EDU (OPC) Private Limited, a company incorporated under the Companies Act, 1956 with its address at 2 - Scheme No. 54, PU-4, Vijay Nagar, Indore - 452010, MP, hereinafter referred to as ‘Platform Owner’, ‘we’, ‘us’, ‘our’.
            </p>

            <p className="text-base md:text-lg leading-relaxed">
              Your use of the platform, services, and tools is governed by these Terms of Use. By accessing, browsing, or using the Platform, you agree to all the terms and conditions outlined here. It is your responsibility to periodically review these Terms of Use for updates.
            </p>

            <p className="text-base md:text-lg leading-relaxed">
              You agree to provide true, accurate, and complete information during registration and are responsible for all actions performed via your account. The platform and services are provided “as is” without warranties. Use the platform at your own risk. Unauthorized use may result in legal action.
            </p>

            <p className="text-base md:text-lg leading-relaxed">
              You agree to pay charges associated with availing services and not to use the platform for unlawful purposes. Third-party links are provided for convenience, and you will be governed by their respective terms. You are entering into a legally binding contract by using our services.
            </p>

            <p className="text-base md:text-lg leading-relaxed">
              You shall indemnify and hold harmless Platform Owner, its affiliates, and employees from any claim, penalty, or legal action arising from your violation of these Terms of Use or applicable laws. Force majeure events may excuse performance delays. Disputes are governed by the laws of India, and the courts of MP have exclusive jurisdiction.
            </p>

            <p className="text-base md:text-lg leading-relaxed">
              <strong>Refund Policy:</strong> No refunds are accepted by HOMENTOR EDU (OPC) Private Limited.
            </p>

          </div>
        </div>
      </div>

    </Layout>
  );
}

export default TermsCondition;
